name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs Material Dependencies
        run: pip install -r requirements-doc.txt

      - name: Build MkDocs
        run: ./build_mkdocs.sh

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
